version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/lsgkm_test.wdl
    testParameterFiles:
      - /exec/lsgkm_test.json
    authors:
      - orcid: 0000-0002-1568-2249
      - name: Dongwon Lee
      - email: dongwon.lee@childrens.harvard.edu
