version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /wdl/lsgkm_pipeline_peak.wdl
    testParameterFiles:
      - /exec/lsgkm_peak_test.json
    authors:
      - orcid: 0000-0002-1568-2249
